version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: "@babel/runtime-corejs3"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.12.5
    - 7.13.10
    - 7.13.6
    - 7.13.7
    - 7.13.9
  - dependency-name: "@size-limit/preset-small-lib"
    versions:
    - 4.10.0
    - 4.10.1
    - 4.9.1
    - 4.9.2
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.2.0
  - dependency-name: "@trigen/scripts"
    versions:
    - 7.0.2
  - dependency-name: mustache
    versions:
    - 4.1.0
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
